# Copyright: © 2022 Dario Passariello <dariopassariello@gmail.com>
# License: MIT

version: "3.1"

services:

  mongodb:
    restart: always
    container_name: dpSuperDemo.mongodb
    build:
      context: ./mongo
      dockerfile: Dockerfile
    volumes:
      - ./mongo/data-node:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth
    networks:
      - vnet

  api:
    restart: always
    container_name: dpSuperDemo.api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    working_dir: /api
    command: node ./bin/start.js
    volumes:
      - ./api:/api
      - /api/node_modules
    entrypoint: ["npm", "start"]
    depends_on:
      - mongodb
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
    networks:
      - vnet

  client_react:
    image: node
    restart: always
    container_name: dpSuperDemo.client.react
    build:
      context: ./client_react
      args:
        API_URL: http://localhost:9000
    ports:
      - "3000:3000"
    working_dir: /client_react/server
    command: node start.js
    volumes:
      - ./client_react:/client_react
      - /client_react/node_modules
    links:
      - api
    networks:
      - vnet

  client_vue:
    image: node
    restart: always
    container_name: dpSuperDemo.client.vue
    build:
      context: ./client_vue
      dockerfile: Dockerfile
      args:
        API_URL: http://localhost:9000
    ports:
      - "3001:3001"
    working_dir: /client_vue
    command: "node ./server/start.js"
    volumes:
      - ./client_vue:/client_vue
      - /client_vue/node_modules
    links:
      - api
    networks:
      - vnet

networks:
  vnet:
    driver: bridge
