export default [{
  ignores: [
    "**/out",
    "**/dist",
    "**/*.d.ts",
    "**/*.min.js",
    "**/private",
    "**/doc",
    "**/#OLD",
    "**/@OLD",
    "**/*.js"
  ],
}, {
  settings: {
    react: {
      version: "detect",
    },

    "import/resolver": "webpack",
  },

  rules: {
    "prefer-rest-params": 0,
    "no-irregular-whitespace": 0,
    "no-var": 0,
    "no-empty": 0,
    "no-console": 0,
    "no-process-exit": 0,
    "no-underscore-dangle": 0,
    "no-param-reassign": 0,
    "no-prototype-builtins": 0,
    "no-unused-vars": 0,
    "no-undef": 0,
    "no-debugger": 0,
    "no-dupe-else-if": 0,
    "no-dupe-class-members": 0,
    "no-useless-escape": 0,
    "node/no-extraneous-require": 0,
    "node/no-unpublished-require": 0,
    "node/no-unsupported-features/es-syntax": 0,
    "node/no-missing-import": 0,
    "node/no-unpublished-import": 0,
    "node/no-unsupported-features/node-builtins": 0,
    "node/no-missing-require": 0,
    "react/prop-types": 0,
    "react/no-string-refs": 0,
    "react/no-find-dom-node": 0,
    "react/display-name": 0,
    "react/jsx-no-undef": 0,
    "promise/no-nesting": 0,
    "promise/no-callback-in-promise": 0,
    "promise/always-return": 0,
    "promise/catch-or-return": 0,
    "promise/no-return-wrap": 0,
    "promise/valid-params": 0,
    "import/export": 0,
    "import/namespace": 0,
    "import/default": 0,
    "import/no-named-as-default": 0,
    "import/no-named-as-default-member": 0,
    "import/no-mutable-exports": 0,
    "import/no-extraneous-dependencies": 0,
    "import/no-unresolved": 0,
    "import/no-duplicates": 0,
    "import/named": 0,
    "unicorn/no-empty-file": 0,
    "unicorn/no-document-cookie": 0,
    "@typescript-eslint/ban-ts-comment": 0,
    "@typescript-eslint/no-var-requires": 0,
    "@typescript-eslint/no-unused-vars": 0,
    "@typescript-eslint/no-empty-function": 0,
    "@typescript-eslint/no-explicit-any": 0,
    "consistent-return": 0,
    "unicorn/no-process-exit": 0,
    "comma-dangle": 0,
    "prefer-const": ["warn"],
    "max-nested-callbacks": ["warn", 4],
    "no-plusplus": 0,

    "operator-linebreak": ["error", "after", {
      overrides: {
        "?": "ignore",
        ":": "ignore",
      },
    }],
  },
}]
