# Copyright: © 2025 Dario Passariello <dariopassariello@gmail.com>
# License: MIT

FROM node:latest
# ARG API_URL

LABEL MAINTAINER="Dario Passariello <dariopassariello@gmail.com>"

RUN mkdir /client
WORKDIR /client/
# ENV API_URL="$API_URL"
COPY ./dist ../client/dist
COPY ./server ../client/server
WORKDIR /client/server
RUN npm install

EXPOSE 3000
CMD ["npm", "run", "start"]
